name: Deploy s3 Bucket

on:
  workflow_dispatch:

env:
   AWS_REGION: ap-southeast-2


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      
      - name: aws assume role
        run: |
          aws sts assume-role --role-arn ${{ secrets.IAMROLE_GITHUB }} --role-session-name AWSCLI-Session
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}  

      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
      #     role-session-name: GitHub-Action-Role
      #     aws-region: ${{ env.AWS_REGION }}
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}