name: Deploy s3 Bucket

on:
  workflow_dispatch:

env:
   AWS_REGION: ap-southeast-2


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      
        - uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.3.4
      


      # - name: Install Terraform
      #   env: 
      #     TERRAFORM_VERSION: "1.3.4"
      #   run: |
      #     tf_version=$TERRAFORM_VERSION
      #     wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
      #     unzip terraform_"$tf_version"_linux_amd64.zip
      #     sudo mv terraform /usr/local/bin/
     
      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          cd terraform/s3 ;
          terraform init -input=false
      
      - name: Terraform validation
        run: 
          cd terraform/s3 ;
          terraform validate

      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          cd terraform/s3 ;
          terraform apply -auto-approve -input=false